//
// Created by Ludwig Andreas on 22.07.2023.
//

#ifndef S21_INCLUDE_LOGGER_PARSE_CONVERTERS_CLASSNAMEPATTERNCONVERTER_H_
#define S21_INCLUDE_LOGGER_PARSE_CONVERTERS_CLASSNAMEPATTERNCONVERTER_H_

class ClassNamePatternConverter {

};

#endif //S21_INCLUDE_LOGGER_PARSE_CONVERTERS_CLASSNAMEPATTERNCONVERTER_H_
