//
// Created by Ludwig Andreas on 22.07.2023.
//

#ifndef S21_INCLUDE_LOGGER_PARSE_CONVERTERS_COLORSTARTPATTERNCONVERTER_H_
#define S21_INCLUDE_LOGGER_PARSE_CONVERTERS_COLORSTARTPATTERNCONVERTER_H_

class ColorStartPatternConverter {

};

#endif //S21_INCLUDE_LOGGER_PARSE_CONVERTERS_COLORSTARTPATTERNCONVERTER_H_
