//
// Created by Ludwig Andreas on 22.07.2023.
//

#ifndef S21_INCLUDE_LOGGER_PARSE_CONVERTERS_COLORENDPATTERNCONVERTER_H_
#define S21_INCLUDE_LOGGER_PARSE_CONVERTERS_COLORENDPATTERNCONVERTER_H_

class ColorEndPatternConverter {

};

#endif //S21_INCLUDE_LOGGER_PARSE_CONVERTERS_COLORENDPATTERNCONVERTER_H_
