//
// Created by Ludwig Andreas on 22.07.2023.
//

#ifndef S21_INCLUDE_LOGGER_PARSE_CONVERTERS_FULLLOCATIONPATTERNCONVERTER_H_
#define S21_INCLUDE_LOGGER_PARSE_CONVERTERS_FULLLOCATIONPATTERNCONVERTER_H_

class FullLocationPatternConverter {

};

#endif //S21_INCLUDE_LOGGER_PARSE_CONVERTERS_FULLLOCATIONPATTERNCONVERTER_H_
