//
// Created by Ludwig Andreas on 22.07.2023.
//

#ifndef S21_INCLUDE_LOGGER_PARSE_CONVERTERS_MESSAGEPATTERNCONVERTER_H_
#define S21_INCLUDE_LOGGER_PARSE_CONVERTERS_MESSAGEPATTERNCONVERTER_H_

class MessagePatternConverter {

};

#endif //S21_INCLUDE_LOGGER_PARSE_CONVERTERS_MESSAGEPATTERNCONVERTER_H_
